[package]
name = "kube-skel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tinytemplate = "1.2"
